# Generated by Django 2.1.7 on 2019-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='detected',
            field=models.BooleanField(default=False),
        ),
    ]
